---
ID: "9a37a33c-21f5-4c60-bdcf-faed01b1957c"
Parent: "0f6e2aa4-fae6-4acc-bb74-576e2e0e7055"
Template: "0f6e2aa4-fae6-4acc-bb74-576e2e0e7055"
Path: /sitecore/templates/Project/demo/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {0F6E2AA4-FAE6-4ACC-BB74-576E2E0E7055}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "3723f032-0c89-41d1-b1fa-09bd8c522edb"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T074315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\lmacura@softserveinc.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\lmacura@softserveinc.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d60c8589-5538-4486-9018-8a452afe5a86"
    - ID: "a52fd683-9a86-4d5d-a8dc-95db00370c7d"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\lmacura@softserveinc.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250609T074322Z
