---
ID: "9a836fd2-7385-4301-95f2-b7228f15fea2"
Parent: "8fe3d37f-5dbd-45d4-8eb8-ec5351efdbdc"
Template: "8fe3d37f-5dbd-45d4-8eb8-ec5351efdbdc"
Path: /sitecore/templates/Project/demo/Partial Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {8FE3D37F-5DBD-45D4-8EB8-EC5351EFDBDC}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9738b983-9812-47ec-8c0d-8f034509d496"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T074315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\lmacura@softserveinc.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\lmacura@softserveinc.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "edbbf86b-0d7a-41ed-b581-3b62d55a7a69"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\lmacura@softserveinc.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250609T074319Z
