---
ID: "b45cf67a-99cb-4060-b4d0-5fff9ba293d1"
Parent: "165cebff-1831-42c0-aa39-eadd875c24d0"
Template: "0f6e2aa4-fae6-4acc-bb74-576e2e0e7055"
Path: /sitecore/content/demo/demo/Home/Products
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{AE214AE4-F39A-44A2-B9F7-D2CAD811CBF1}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{45CF460D-695C-4EB2-A691-01C9F182A354}"
              p:before="*"
              s:ds="local:/Data/Our Products"
              s:id="{D6B9F790-4C5A-4D0F-A770-B72D52C565B3}"
              s:par="Heading"
              s:ph="headless-main" />
            <r
              uid="{F94B66B1-1867-4296-8862-1601F2F75782}"
              p:after="*[1=2]"
              s:ds="local:/Data/Text 1"
              s:id="{9C6D53E3-FE57-4638-AF7B-6D68304C7A94}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B5F62028C-9537-400C-8ACE-726C19BE6E51%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="/headless-main/headless-section-{45CF460D-695C-4EB2-A691-01C9F182A354}-0" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250617T122630Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\yseme2@softserveinc.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\yseme2@softserveinc.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bd52709e-5044-45de-97cd-47b01274e5b0"
    - ID: "a52fd683-9a86-4d5d-a8dc-95db00370c7d"
      Hint: Title
      Value: Products
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\yseme2@softserveinc.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250618T122639Z
